<?php

namespace controllers;

use Sweetphp\Routing\Controller;

class BaseController extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}